### ISSUE TITLE
Thumbnails don't work

### ISSUE THREAD

**Issue by Noramire** [unreadablewxy/fs-viewer#26]
https://i.imgur.com/WhSauCZ.png
https://i.imgur.com/tqFoSC3.png

Windows 10 x64

**Comment by unreadablewxy** [comment]
Did you by any chance configure "Always show icons, never thumbnails" in folder options? That disables the system thumbnailer, which could create this error

Looks like spacing is busted too. Suppose your scroll bars are not default width too. 0.0.1b assumes 17 px wide, this is going to be fixed in in a subsequent release

**Comment by Noramire** [comment]
@unreadablewxy, on the moment I posted the issue this option was enabled. I tried to disable it, but seems like it doesn't response anyhow.

**Comment by unreadablewxy** [comment]
was able to repro the freeze bug. Found a fix for it that aligns with [design goals](https://github.com/unreadablewxy/fs-viewer/wiki/How-Tagging-Works). Will incorporate into 0.0.3

**Comment by unreadablewxy** [comment]
Resolved in 0.0.3
